public  class AppuntamentoDisponibilitaService {
    
  /*  public static void cercaDisponibilita(List<XCS_Desk__c> desks, String dayOfWeek, Map<Id, Object> mapDesk){
         System.debug(' ############### running EventDomaine getSlotDesk  dayOfWeek '+dayOfWeek);
         String query = 'SELECT Id, Desk__c, StartTime__c, EndTime__c FROM XCS_DeskItem__c WHERE '+dayOfWeek +'= true AND Desk__c IN :desks' ;
        List<XCS_DeskItem__c> items = Database.query(query);
        System.debug('################# '+items);
        if(items.size() == 0 ){
            AppuntamentoError.hasError = true;
            AppuntamentoError.errorMessage = 'Appuntamento not Available at '+dayOfWeek;
            return;
        }
        else{
            
        }
    }*/

}