@isTest
public class OCS_recuperaInfoPraticaResponseTest {
    
    @isTest
    public static void test() {
        OCS_recuperaInfoPraticaResponse obj = new OCS_recuperaInfoPraticaResponse();
        
        OCS_recuperaInfoPraticaResponse.RecuperaInfoPraticaResponse oTwo = new OCS_recuperaInfoPraticaResponse.RecuperaInfoPraticaResponse();
        
        obj.recuperaInfoPraticaResponse = oTwo;
        oTwo.dataLiquidazione ='';
        oTwo.flagAssicLLOYD='';
        oTwo.nota='';
        oTwo.prodotto='';
        oTwo.targa='';
        oTwo.telaio='';
        oTwo.annoMeseImmatricolazione='';
        oTwo.marcaModello='';
        oTwo.descrizioneBene='';
        oTwo.valoreBene='';
        oTwo.cognome='';
        oTwo.nome='';
        oTwo.ragioneSociale='';
        oTwo.finanziato='';
        oTwo.sottogruppo='';
        oTwo.ramoGruppo='';
        oTwo.ateco='';
        oTwo.coniuge='';
        oTwo.tipoProdotto='';   
    }
    
}