@isTest
public class OCS_OCS_COPSVDTA_V1RequestTest {
    @isTest
    public static void test() {       
        OCS_OCS_COPSVDTA_V1Request r = new OCS_OCS_COPSVDTA_V1Request();
        r.authorization = '';
        r.Copsvdtarequest.mftcopsdta_PRATICA = 0;
        r.Copsvdtarequest.mftcopsdta_TARGA = '';
        r.Copsvdtarequest.mftcopsdta_TELAIO = '';
        r.Copsvdtarequest.mftcopsdta_MARCA = '';
        r.Copsvdtarequest.mftcopsdta_MODELLO = '';
        r.Copsvdtarequest.mftcopsdta_DATA_IMMATRIC = '';
        r.Copsvdtarequest.msflogon_TMP_KEY = '';
        r.Copsvdtarequest.msfilogon_SENDER_TIPO = '';
        r.Copsvdtarequest.msfilogon_CANALE_ACQUISIZ = '';
        r.Copsvdtarequest.msfilogon_TIPO_CARICAMENTO = '';
        r.Copsvdtarequest.mftcopsdta_CILINDRATA = 0;
        r.Copsvdtarequest.msfilogon_SENDER_CODICE = 0;           
    }    
}