@isTest
public class OCSPraticaFuturoTest {
    
    @isTest
    public static void test() {
        OCSPraticaFuturo o = new OCSPraticaFuturo();
        
        o.agenteCod='';
        o.agenteRagSoc='';
        o.assicImpiegoCod='';
        o.assicImpiegoRagSoc='';
        o.assicVitaCod='';
        o.assicVitaRagSoc='';
        o.aziendaCap='';
        o.aziendaCod='';
        o.aziendaIndirizzo='';
        o.aziendaLocalita='';
        o.aziendaProv='';
        o.aziendaRagSoc='';
        o.aziendaSedeCap='';
        o.aziendaSedeCod='';
        o.aziendaSedeIndirizzo='';
        o.aziendaSedeLocalita='';
        o.aziendaSedeProv='';
        o.aziendaSedeRagSoc='';
        o.bancaCod='';
        o.bancaRagSoc='';
        o.classifRecupero='';
        o.codAttributoPratica='';
        o.codCliente='';
        o.codRecuperatore='';
        o.codStatoPratica='';
        o.dataCaricamento='';
        o.dataContratto='';
        o.dataEstinzioneAnticipata='';
        o.desAttributoPratica='';
        o.desRecuperatore='';
        o.desStatoPratica='';
        o.filBancaCod='';
        o.filBancaRagSoc='';
        o.flagRecupero='';
        o.numPratica='';
        o.subAgenteCod='';
        o.subAgenteRagSoc='';
        o.tipoPratica='';
        

    }

}