@isTest
public class OCSRecuperaMovAutViaggiantiRequestTest {
    
    @isTest
    public static void test() {
        
        OCSRecuperaMovAutViaggiantiRequest m = new OCSRecuperaMovAutViaggiantiRequest();
        m.recuperaMovimentiAutorizzazioniViaggiantiRequest.provenienza = '';
        m.recuperaMovimentiAutorizzazioniViaggiantiRequest.tipoIntermediario = '';
        m.recuperaMovimentiAutorizzazioniViaggiantiRequest.intermediario = '';       
        m.recuperaMovimentiAutorizzazioniViaggiantiRequest.emettitore = '';        
        m.recuperaMovimentiAutorizzazioniViaggiantiRequest.numPratica = '';
        m.recuperaMovimentiAutorizzazioniViaggiantiRequest.pan = '';        
        m.recuperaMovimentiAutorizzazioniViaggiantiRequest.dataRegistrazione = '';
        m.recuperaMovimentiAutorizzazioniViaggiantiRequest.tipoRecord = '';
        m.recuperaMovimentiAutorizzazioniViaggiantiRequest.progressivo = '';
        m.recuperaMovimentiAutorizzazioniViaggiantiRequest.protocollo = '';
        m.recuperaMovimentiAutorizzazioniViaggiantiRequest.riga = '';
        m.recuperaMovimentiAutorizzazioniViaggiantiRequest.statoAutorizzazione = '';
        m.recuperaMovimentiAutorizzazioniViaggiantiRequest.esitoAutorizzazione = '';
        m.recuperaMovimentiAutorizzazioniViaggiantiRequest.dataAutorizzazione = '';
        m.recuperaMovimentiAutorizzazioniViaggiantiRequest.numElementi = '';
        m.recuperaMovimentiAutorizzazioniViaggiantiRequest.flagMovimenti = '';
        m.recuperaMovimentiAutorizzazioniViaggiantiRequest.flagAutorizzazioni = '';
        m.recuperaMovimentiAutorizzazioniViaggiantiRequest.utente = ''; 
        m.recuperaMovimentiAutorizzazioniViaggiantiRequest.tipoChiave = '';
        
    }
        
}