@isTest
public class OCSRecuperaDatiPostvenditaRequestTest {
    
    @isTest
    public static void test() {
    
        OCSRecuperaDatiPostvenditaRequest r = new OCSRecuperaDatiPostvenditaRequest();
        r.numPratica = '';
        r.flagInfoCliente = '';
        r.filtroTipoPratica = '';
        r.codCliente = '';
        r.cognomeCliente = '';
        r.nomeCliente = '';
        r.dataNascitaCliente = '';
        r.codFiscaleCliente = '';
        r.pan = '';
        r.telefonoCliente = '';
        r.faxCliente = '';
        r.emailCliente = '';
        r.provinciaCliente = '';
        r.ragioneSociale = '';        
        
        
    }
    
}