@isTest
public class OCSRecuperaPacchettiServiziRequestTest {
    
    @isTest
    public static void test() {
        
        OCSRecuperaPacchettiServiziRequest p = new OCSRecuperaPacchettiServiziRequest();
        OCSRecuperaPacchettiServiziRequest.RecuperaPacchettiServiziRequestDTO ps = new  OCSRecuperaPacchettiServiziRequest.RecuperaPacchettiServiziRequestDTO();
        ps.numPratica = '';
        ps.tipoPratica = '';
        
    }
    
}