@isTest
public class OCSRecuperaDatiClienteResponseTest {
       
    @isTest
    public static void test(){
        OCSRecuperaDatiClienteResponse r = new OCSRecuperaDatiClienteResponse();
       
        r.recuperaDatiClienteResponse.telefonoCasa = '2';
        r.recuperaDatiClienteResponse.telefonoAlternativo = '2';
        r.recuperaDatiClienteResponse.telCellulare = '2';
        r.recuperaDatiClienteResponse.fax = '2';
        r.recuperaDatiClienteResponse.privacyOffCommInterne = '2';
        r.recuperaDatiClienteResponse.privacyOffCommIntAut = '2';
        r.recuperaDatiClienteResponse.privacyOffCommEsterne = '2';
        r.recuperaDatiClienteResponse.privacyOffCommEstAut = '2';
        r.recuperaDatiClienteResponse.privacyServiziAltri = '2';
        r.recuperaDatiClienteResponse.privacyDatiSensibili = '2';
        r.recuperaDatiClienteResponse.privacyIstruttPratiche = '2';
        r.recuperaDatiClienteResponse.privacyRilevQualita = '2';
        r.recuperaDatiClienteResponse.privacyConsInfoSic = '2';
        r.recuperaDatiClienteResponse.privacyRichCanc = '2';
        r.recuperaDatiClienteResponse.privacyDataIstruttPratiche = '2';
        r.recuperaDatiClienteResponse.privacyDataOfferte = '2';
        r.recuperaDatiClienteResponse.privacyDataSensibili = '2';
        r.recuperaDatiClienteResponse.privacyDataConsSic = '2';
        r.recuperaDatiClienteResponse.privacyNoteConsSic = '2';
        
    }
}