/**
 * @File Name          : PV3267VariazioneIndirizziTest.cls
 * @Description        : 
 * @Author             : Raffaele Prudenzano
 * @Group              : 
 * @Last Modified By   : Raffaele Prudenzano
 * @Last Modified On   : 11/11/2019, 10:01:02
 * @Modification Log   : 
 * Ver       Date            Author      		    Modification
 * 1.0    11/11/2019   Raffaele Prudenzano     Initial Version
**/

@isTest
public with sharing class PV3267VariazioneIndirizziTest {
    public PV3267VariazioneIndirizziTest() {

    }
}