public class XCS_Indirizzo {
    
    @AuraEnabled public String tipoIndirizzo {get;set;}
    @AuraEnabled public String indirizzo {get;set;}
    @AuraEnabled public String civico {get;set;}
    @AuraEnabled public String cap {get;set;}
    @AuraEnabled public String localita {get;set;}
    @AuraEnabled public String provincia {get;set;}
    @AuraEnabled public String nazione {get;set;}
    @AuraEnabled public String capRischio {get;set;}
    
}